FROM bananocoin/banano-build:latest-alpine

ARG NETWORK=live
ARG TRAVIS_TAG=DEV_BUILD
ARG CI_BUILD=OFF
ADD ./ /tmp/src

# Build bananode
RUN mkdir /tmp/build && \
    cd /tmp/build && \
    cmake /tmp/src -DCI_BUILD=${CI_BUILD} -DACTIVE_NETWORK=nano_${NETWORK}_network \
    -DNANO_ROCKSDB=ON -DNANO_POW_SERVER=ON -DROCKSDB_LIBRARIES=/usr/local/rocksdb/lib/librocksdb.a \
    -DROCKSDB_INCLUDE_DIRS=/usr/local/rocksdb/include && \
    make bananode -j$(nproc) && \
    make banano_rpc -j$(nproc) && \
    make nano_pow_server -j$(nproc) && \
    cd .. && \
    echo ${NETWORK} > /etc/nano-network

# Copy binaries to alpine base
FROM alpine:3.11.6

# Curl is useful to run monitoring from inside the container
RUN apk --no-cache add curl

COPY --from=0 /tmp/build/bananode /usr/bin
COPY --from=0 /tmp/build/banano_rpc /usr/bin
COPY --from=0 /tmp/build/nano_pow_server /usr/bin
COPY --from=0 /etc/nano-network /etc
COPY docker/node/entry.sh /usr/bin/entry.sh
COPY docker/node/config /usr/share/nano/config
RUN chmod +x /usr/bin/entry.sh

WORKDIR /root
USER root

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["/usr/bin/entry.sh bananode daemon -l"]