FROM nanocurrency/nano-env:base

RUN apt-get update -qq && apt-get install -yqq \
    clang-3.9 lldb-3.9 git

RUN git clone https://github.com/facebook/rocksdb.git && \
    cd rocksdb && \
    make static_lib && \
    make install

ENV CXX=/usr/bin/clang++
ENV CC=/usr/bin/clang
RUN ln -s /usr/bin/clang-3.9 /usr/bin/clang
RUN ln -s /usr/bin/clang++-3.9 /usr/bin/clang++
RUN update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
RUN update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100
ENV BOOST_ROOT=/usr/local
ADD util/build_prep/bootstrap_boost.sh bootstrap_boost.sh

RUN ./bootstrap_boost.sh -m -c

RUN rm bootstrap_boost.sh
