ARG ENV_REPOSITORY=nanocurrency/nano-env
FROM ${ENV_REPOSITORY}:base

RUN apt-get update -qq && apt-get install -yqq \
clang \
lldb \
git \
libboost-all-dev

ENV CXX=/usr/bin/clang++
ENV CC=/usr/bin/clang
RUN update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
RUN update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100

ARG REPOSITORY=nanocurrency/nano-node
LABEL org.opencontainers.image.source https://github.com/$REPOSITORY
