FROM rockylinux:8

WORKDIR /workspace

RUN yum update -y
RUN yum install -y git wget openssl bzip2
RUN yum install -y rpm-build
RUN yum install -y glibc-devel glibc-headers make which
RUN yum install -y cmake gcc-toolset-12
RUN yum install -y python38
