FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq && apt-get install -yqq \
build-essential \
g++ \
wget \
python3 \
zlib1g-dev \
cmake \
git

RUN apt-get update -qq && apt-get install -yqq \
qtbase5-dev \
qtchooser \
qt5-qmake \
qtbase5-dev-tools \
valgrind \
xorg xvfb xauth xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic

ARG REPOSITORY=nanocurrency/nano-node
LABEL org.opencontainers.image.source https://github.com/$REPOSITORY
