name: Develop Branch Dockers Deploy

on:
  push:
    branches:
      - develop

jobs:
  linux_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 #v3.1.0
        with:
          submodules: "recursive"
      - name: Fetch Deps
        run: ci/actions/linux/install_deps.sh
      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Deploy Docker (ghcr.io)
        run: ci/actions/linux/ghcr_push.sh
      - name: Deploy Docker (nanocurrency/nano-env)
        run: ci/actions/linux/docker-deploy.sh
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
