if("${CMAKE_SIZEOF_VOID_P}" EQUAL "8")
  set(WIN_REDIST vc_redist.x64.exe)
else()
  set(WIN_REDIST vc_redist.x86.exe)
endif()
set(CPACK_NSIS_EXTRA_INSTALL_COMMANDS
    "ExecWait '\\\"$INSTDIR\\\\${WIN_REDIST}\\\" /quiet /norestart'
                                            WriteRegDWORD HKLM 'SYSTEM\\\\CurrentControlSet\\\\Services\\\\EventLog\\\\Nano\\\\Nano${NANO_PREFIX}' 'TypesSupported' '0x7'
                                            WriteRegStr HKLM 'SYSTEM\\\\CurrentControlSet\\\\Services\\\\EventLog\\\\Nano\\\\Nano${NANO_PREFIX}' 'EventMessageFile' '$INSTDIR\\\\nano_wallet.exe'"
)
set(CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS
    "DeleteRegKey HKLM 'SYSTEM\\\\CurrentControlSet\\\\Services\\\\EventLog\\\\Nano${NANO_PREFIX}'"
)
set(CPACK_NSIS_MUI_ICON ${CMAKE_SOURCE_DIR}/Nano.ico)
set(CPACK_NSIS_DISPLAY_NAME "Nano${NANO_PREFIX}")
set(CPACK_NSIS_URL_INFO_ABOUT "https://nano.org")
set(CPACK_NSIS_CONTACT "info@nano.org")
set(CPACK_NSIS_MENU_LINKS "nano_wallet.exe" "Nano Wallet" "https://nano.org"
                          "Nano website")
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
get_target_property(Qt5WindowsPlugin Qt5::QWindowsIntegrationPlugin LOCATION)
get_filename_component(Qt5_bin_DIR ${Qt5_DIR}/../../../bin ABSOLUTE)
install(TARGETS nano_wallet DESTINATION .)
install(TARGETS nano_wallet_com DESTINATION .)
if(NANO_SHARED_BOOST)
  foreach(boost_lib IN LISTS Boost_LIBRARIES)
    if(${CMAKE_BUILD_TYPE} MATCHES "Rel")
      string(REGEX MATCH "(.+/.*boost_[^-]+-.+-mt-x64.+\)(.lib|a)"
                   boost_lib_name ${boost_lib})
      set(boost_dll "${CMAKE_MATCH_1}.dll")
      if(${boost_dll} MATCHES "boost")
        install(FILES ${boost_dll} DESTINATION .)
      endif()
    else()
      string(REGEX MATCH "(.+/.*boost_[^-]+-.+-mt-.+-x64.+\)(.lib|a)"
                   boost_lib_name ${boost_lib})
      set(boost_dll "${CMAKE_MATCH_1}.dll")
      if(${boost_dll} MATCHES "boost")
        install(FILES ${boost_dll} DESTINATION .)
      endif()
    endif()
  endforeach(boost_lib)
endif()
if(NANO_POW_SERVER)
  install(TARGETS nano_pow_server DESTINATION .)
  install(DIRECTORY ${PROJECT_SOURCE_DIR}/nano-pow-server/public DESTINATION .)
endif()
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/${WIN_REDIST} DESTINATION .)
install(FILES ${Qt5_bin_DIR}/libGLESv2.dll DESTINATION .)
install(FILES ${Qt5_bin_DIR}/Qt5Core.dll DESTINATION .)
install(FILES ${Qt5_bin_DIR}/Qt5Gui.dll DESTINATION .)
install(FILES ${Qt5_bin_DIR}/Qt5Widgets.dll DESTINATION .)
install(FILES ${Qt5_bin_DIR}/Qt5WinExtras.dll DESTINATION .)
install(FILES ${Qt5WindowsPlugin} DESTINATION platforms)
